# Generated by Django 3.0.8 on 2020-09-15 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bag', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bag',
            name='quantity',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
