# Generated by Django 3.0.8 on 2020-09-16 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bag', '0003_coupon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
