# Generated by Django 3.1.1 on 2020-09-03 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='delivery',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
