# Generated by Django 3.1.1 on 2020-09-03 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200903_1138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='delivery',
            new_name='delivery_time',
        ),
    ]
