# Generated by Django 3.0.8 on 2020-09-13 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_best_selling_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Best_selling_product',
            new_name='Top_selling_product',
        ),
    ]
